import os
import requests

BOT_TOKEN = os.getenv("BOT_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

def send_signal(signal, confidence):
    if not BOT_TOKEN or not CHAT_ID:
        print("Telegram secrets not found.")
        return

    message = f"""
🤖 ISDORE AI BOT

Signal: {signal}
Confidence: {confidence}%

Generated by Version 3
"""

    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

    requests.post(url, data={
        "chat_id": CHAT_ID,
        "text": message
    })
